apiVersion: v1
kind: Service
metadata:
  name: workflow-dispatcher
  labels:
    name: workflow-dispatcher
spec:
  type: NodePort
  ports:
  - name: api
    port: 8080
    targetPort: 8080
  selector:
    name: workflow-dispatcher

